[package]
name = "data_analysis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
coingecko = "1.0.1"
tokio = { version = "0.2.0", features = ["full"]  }
yahoo-finance = "0.3.0"
